name: Release

on:
  workflow_dispatch:
    inputs:
      packageEnv:
        description: 'controls what type of version number is used.'
        required: true
        default: 'nightly'
        type: choice
        options:
        - nightly
        - staging
        - production
      version:
        description: 'semantic version number, like 0.0.1. Do not include suffix data.'
        required: true
        type: string

jobs:
  rerun-pr-steps:
    uses: Beamable/solana-example/.github/workflows/pr.yml@develop
  build:
    needs: rerun-pr-steps
    timeout-minutes: 30
    runs-on: ubuntu-latest
    concurrency:
      group: release
      cancel-in-progress: true
    steps: 
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: create version
        run: |
          VERSION=${{ github.event.inputs.version }}
          echo "::set-output name=value::${VERSION:-github.sha}"
      - name: set package version
        run: npm version ${VERSION} --allow-same-version
      - name: check package json
        run: cat ./Packages/com.beamable.solana/package.json
      - name: rename samples folder
        run: mv ./Packages/com.beamable.solana/Samples ./Packages/com.beamable.solana/Samples~
      - name: check package folers
        run: ls ./Packages/com.beamable.solana