name: Release

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      version:
        description: 'semantic version number, like 0.0.1'
        required: false
        default: 0.0.0
        type: string
      prechecks:
        description: 'should run build and test checks'
        required: false
        type: boolean
        default: true

jobs:
  rerun-pr-steps:
    if: github.event.inputs.prechecks == true
    uses: Beamable/solana-example/.github/workflows/pr.yml@develop
    secrets: inherit
  build:
    needs: rerun-pr-steps
    if: always()
    timeout-minutes: 30
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    concurrency:
      group: release
      cancel-in-progress: true
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: set package version
        run: |
          cd ./Packages/com.beamable.solana/
          VERSION=${{inputs.version}}
          npm version ${VERSION:-0.0.0-PREVIEW.NIGHTLY-$(date +'%Y%m%d%H%s')} --allow-same-version
      - name: check package json
        run: cat ./Packages/com.beamable.solana/package.json
      - name: rename samples folder
        run: |
          mv ./Packages/com.beamable.solana/Samples ./Packages/com.beamable.solana/Samples~
          rm ./Packages/com.beamable.solana/Samples.meta
      - name: check package folers
        run: ls ./Packages/com.beamable.solana
      - name: tag and push
        run: |
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git status
          git tag
          git describe