name: Release

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      version:
        description: 'semantic version number, like 0.0.1. Do not include suffix data.'
        required: false
        type: string
      prechecks:
        description: 'should run build and test checks'
        required: false
        type: boolean
        default: true

jobs:
  rerun-pr-steps:
    if: github.event.inputs.prechecks == true
    uses: Beamable/solana-example/.github/workflows/pr.yml@develop
    secrets: inherit
  build:
    needs: rerun-pr-steps
    if: always()
    timeout-minutes: 30
    runs-on: ubuntu-latest
    environment: ${{github.event.input.environment}}
    concurrency:
      group: release
      cancel-in-progress: true
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: set package version
        run: |
          cd ./Packages/com.beamable.solana/
          VERSION=${{github.event.input.version}}
          
          npm version ${VERSION:-0.0.0-PREVIEW.NIGHTLY-$(date +'%Y%m%d%HH%s')} --allow-same-version
      - name: check package json
        run: cat ./Packages/com.beamable.solana/package.json
      - name: rename samples folder
        run: |
          mv ./Packages/com.beamable.solana/Samples ./Packages/com.beamable.solana/Samples~
          mv ./Packages/com.beamable.solana/Samples.meta ./Packages/com.beamable.solana/Samples~.meta
      - name: check package folers
        run: ls ./Packages/com.beamable.solana
      - name: check registry
        run: |
          echo hello
          echo ${{vars.NPM_REGISTRY}}
          echo world
          echo ${{github.event.input.environment}}
          echo byt
      - name: publish
        env: 
          NPM_AUTH: ${{secrets.NPM_AUTH}}
          NPM_REGISTRY: ${{vars.NPM_REGISTRY}}
        run: |
          cd ./Packages/com.beamable.solana/
          echo ${NPM_REGISTRY}
          echo ${NPM_AUTH}
          npm publish .
          